# Generated by Django 4.2.7 on 2024-04-04 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisualData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price_sum",
                    models.TextField(
                        blank=True, help_text="Sum of prices of all drugs", null=True
                    ),
                ),
                (
                    "total_drug_count",
                    models.TextField(
                        blank=True, help_text="Total count of drugs", null=True
                    ),
                ),
                (
                    "total_ingredient_count",
                    models.TextField(
                        blank=True,
                        help_text="Total number of unique ingredients",
                        null=True,
                    ),
                ),
                (
                    "total_brand_count",
                    models.TextField(
                        blank=True,
                        help_text="Total number of unique brand names",
                        null=True,
                    ),
                ),
                (
                    "total_country_count",
                    models.TextField(
                        blank=True,
                        help_text="Total number of unique countries",
                        null=True,
                    ),
                ),
                (
                    "total_agent_count",
                    models.TextField(
                        blank=True, help_text="Total number of unique agents", null=True
                    ),
                ),
                (
                    "top_expensive_drugs",
                    models.TextField(
                        blank=True,
                        help_text="Top 20 most expensive brand names",
                        null=True,
                    ),
                ),
                (
                    "top_subsidized_drugs",
                    models.TextField(
                        blank=True, help_text="Top 5 most subsidized drugs", null=True
                    ),
                ),
                (
                    "common_atcs",
                    models.TextField(
                        blank=True, help_text="Top 5 common ATCs", null=True
                    ),
                ),
                (
                    "common_ingredients",
                    models.TextField(
                        blank=True, help_text="Top 5 common ingredients", null=True
                    ),
                ),
                (
                    "common_brand_names",
                    models.TextField(
                        blank=True, help_text="Top 5 common brands", null=True
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp for the last update",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Visual Data",
            },
        ),
    ]
