# Generated by Django 4.2.7 on 2024-04-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visual", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VisualData",
        ),
    ]
