# Generated by Django 4.2.7 on 2024-04-05 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("visual", "0002_delete_visualdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price_sum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sum of prices of all drugs",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "total_drug_count",
                    models.IntegerField(
                        blank=True, help_text="Total count of drugs", null=True
                    ),
                ),
                (
                    "total_ingredient_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of unique ingredients",
                        null=True,
                    ),
                ),
                (
                    "total_brand_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of unique brand names",
                        null=True,
                    ),
                ),
                (
                    "total_country_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of unique countries",
                        null=True,
                    ),
                ),
                (
                    "total_agent_count",
                    models.IntegerField(
                        blank=True, help_text="Total number of unique agents", null=True
                    ),
                ),
                (
                    "total_resparty_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of responsible parties",
                        null=True,
                    ),
                ),
                (
                    "total_rescountry_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of responsible countries",
                        null=True,
                    ),
                ),
                (
                    "total_subsidy_sum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sum of subsidies of all drugs",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "top_expensive_drugs",
                    models.JSONField(
                        blank=True,
                        help_text="Top 20 most expensive brand names",
                        null=True,
                    ),
                ),
                (
                    "top_subsidized_drugs",
                    models.JSONField(
                        blank=True, help_text="Top 5 most subsidized drugs", null=True
                    ),
                ),
                (
                    "common_atcs",
                    models.JSONField(
                        blank=True, help_text="Top 5 common ATCs", null=True
                    ),
                ),
                (
                    "common_ingredients",
                    models.JSONField(
                        blank=True, help_text="Top 5 common ingredients", null=True
                    ),
                ),
                (
                    "common_brand_names",
                    models.JSONField(
                        blank=True, help_text="Top 5 common brands", null=True
                    ),
                ),
                (
                    "common_countries",
                    models.JSONField(
                        blank=True,
                        help_text="Top 5 countries with the most drugs",
                        null=True,
                    ),
                ),
                (
                    "common_agents",
                    models.JSONField(
                        blank=True,
                        help_text="Top 5 agents representing the most drugs",
                        null=True,
                    ),
                ),
                (
                    "common_resparties",
                    models.JSONField(
                        blank=True, help_text="Top 5 responsible parties", null=True
                    ),
                ),
                (
                    "common_rescountries",
                    models.JSONField(
                        blank=True, help_text="Top 5 responsible countries", null=True
                    ),
                ),
                (
                    "drug_price_distribution",
                    models.JSONField(
                        blank=True, help_text="Distribution of drug prices", null=True
                    ),
                ),
                (
                    "drug_subsidy_distribution",
                    models.JSONField(
                        blank=True,
                        help_text="Distribution of drug subsidies",
                        null=True,
                    ),
                ),
                (
                    "atc_classification_count",
                    models.JSONField(
                        blank=True,
                        help_text="Count of drugs per ATC classification",
                        null=True,
                    ),
                ),
                (
                    "ingredient_usage_count",
                    models.JSONField(
                        blank=True, help_text="Count of drugs per ingredient", null=True
                    ),
                ),
                (
                    "brand_name_usage_count",
                    models.JSONField(
                        blank=True, help_text="Count of drugs per brand name", null=True
                    ),
                ),
                (
                    "top_agents_with_brandnames",
                    models.JSONField(
                        blank=True,
                        help_text="Top 10 agents with the number and names of BrandNames for each",
                        null=True,
                    ),
                ),
                (
                    "top_countries_with_brandnames",
                    models.JSONField(
                        blank=True,
                        help_text="Top 10 countries with the number and names of BrandNames for each",
                        null=True,
                    ),
                ),
                (
                    "top_manufacturers_with_brandnames",
                    models.JSONField(
                        blank=True,
                        help_text="Top 10 manufacturers with the number and names of BrandNames for each",
                        null=True,
                    ),
                ),
                (
                    "top_countries_with_manufacturers",
                    models.JSONField(
                        blank=True,
                        help_text="Top 10 countries with the number and names of manufacturers for each",
                        null=True,
                    ),
                ),
                (
                    "top_resparties_with_brandnames",
                    models.JSONField(
                        blank=True,
                        help_text="Top 10 responsible parties with the number and names of BrandNames for each",
                        null=True,
                    ),
                ),
                (
                    "top_rescountries_with_resparties",
                    models.JSONField(
                        blank=True,
                        help_text="Top 10 responsible countries with the number and names of responsible parties for each",
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp for the last update",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Visual Data",
            },
        ),
    ]
