# Generated by Django 4.2.7 on 2024-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("visual", "0004_delete_visualdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedsAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agenam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_agent",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsAtc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atcnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_atc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsBg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bgnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_bg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsDosage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_dosage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subsidy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("excdate", models.DateField()),
                ("owner_id", models.IntegerField()),
            ],
            options={
                "db_table": "meds_drug",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_form",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_ingredient",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mannam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_manufacturer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_name",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_presentation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsRegnum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_regnum",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsRescountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rescounam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_rescountry",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsResparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resparnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_resparty",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsStrength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strenam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_strength",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedsSubsidy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subnam", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "meds_subsidy",
                "managed": False,
            },
        ),
    ]
