# Generated by Django 4.2.7 on 2024-04-02 19:23

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0002_falserawdata_delete_rawdata"),
    ]

    operations = [
    ]

