# Generated by Django 4.2.7 on 2024-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0003_truerawdata_delete_falserawdata"),
    ]



    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingnam",
            field=models.CharField(max_length=550, null=True, unique=True),
        ),
    ]
