# Generated by Django 4.2.7 on 2024-04-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0004_alter_ingredient_ingnam"),
    ]

    operations = [
    ]

