# Generated by Django 4.2.7 on 2024-04-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0005_delete_truerawdata"),
    ]

    operations = [






    ]
