# Generated by Django 4.2.7 on 2024-04-04 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0006_regnum_drug_regnum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rescountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rescounam", models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resparnam", models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="drug",
            name="strength",
        ),
        migrations.AddField(
            model_name="drug",
            name="rescountry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meds.rescountry",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="resparty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meds.resparty",
            ),
        ),
    ]
