# Generated by Django 4.2.7 on 2024-04-04 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0008_alter_ingredient_ingnam"),
    ]


