# Generated by Django 4.2.7 on 2024-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0010_regnum_drug_regnum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingnam",
            field=models.TextField(null=True),
        ),
    ]
