# Generated by Django 4.2.7 on 2024-04-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0012_alter_ingredient_ingnam"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atc1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atc1nam", models.CharField(max_length=255, null=True, unique=True)),
                ("atc1desc", models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Atc2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atc2nam", models.CharField(max_length=255, null=True, unique=True)),
                ("atc2desc", models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Atc3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atc3nam", models.CharField(max_length=255, null=True, unique=True)),
                ("atc3desc", models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Atc4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atc4nam", models.CharField(max_length=255, null=True, unique=True)),
                ("atc4desc", models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="drug",
            name="atc1",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="meds.atc1"
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="atc2",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="meds.atc2"
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="atc3",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="meds.atc3"
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="atc4",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="meds.atc4"
            ),
        ),
    ]
