# Generated by Django 4.2.7 on 2024-04-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0013_atc1_atc2_atc3_atc4_drug_atc1_drug_atc2_drug_atc3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="price17424",
            field=models.IntegerField(null=True),
        ),
    ]
