# Generated by Django 4.2.7 on 2024-03-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="votes",
        ),
        migrations.RemoveField(
            model_name="question",
            name="pub_date",
        ),
    ]
