# Generated by Django 4.2.7 on 2024-03-25 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_choice_votes_remove_question_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
            preserve_default=False,
        ),
    ]
