# Generated by Django 4.2.7 on 2024-03-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0002_alter_cat_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="comments",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
